### ISSUE TITLE
AttributeError: 'LexToken' object has no attribute 'skip'

### ISSUE THREAD

**Issue by zopyx** [dabeaz/ply#100]
I am currently trying to port this parser

https://github.com/zopyx/zopyx.txng3.core/blob/python-3/zopyx/txng3/core/parsers/english2.py

from some old lex/yacc version (from 2007) to latest PLY release.

Running some existing tests gives me the following error:

```
$HOME/src/zopyx.txng3.core/bin/py english2.py
Generating LALR tables
WARNING: 99 shift/reduce conflicts
WARNING: 13 reduce/reduce conflicts
WARNING: reduce/reduce conflict in state 18 resolved using rule (expr -> NOT factor)
WARNING: rejected rule (expr -> factor) in state 18
--------------------------------------------------------------------------------
>> title::phrase(the zope book) and author::and(michel pelletier)
Traceback (most recent call last):
  File "/home/ajung/src/zopyx.txng3.core/bin/py", line 59, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "english2.py", line 410, in <module>
    print(EnglishQueryParser.lexer(query))
  File "english2.py", line 106, in lexer
    tok = lex.token()
  File "/home/ajung/.buildout/eggs/ply-3.9-py3.5.egg/ply/lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
  File "english2.py", line 236, in t_error
    t.skip(1)
AttributeError: 'LexToken' object has no attribute 'skip'

```

**Comment by kirbyfan64** [comment]
Try `t.lexer.skip(1)`.

**Comment by dabeaz** [comment]
Yes. Tokens have a 'lexer' instance attached them.  You should use `t.lexer.skip(1)`.
