### ISSUE TITLE
"could not get source" when frozen by py2app

### ISSUE THREAD

**Issue by riggsd** [dabeaz/ply#108]
`py2app` is a framework which rolls up Python source, all its dependencies, and the Python interpreter itself into a distributable Mac OS X "executable" .app. The dependencies and standard library get precompiled to .pyc bytecode, the source .py files get discarded, and everything gets wrapped up into a .zip file; runtime imports are resolved from within the .zip file. This is (probably) very similar to how `pyinstaller`, `cx_freeze`, and other Python distribution-makers work.

My own application depends on `sounddevice`, which depends on `CFFI`, which depends on `pycparser`... which depends on `plc`. Whew! When I attempt to package my application with `py2app`, I get the following failure at runtime:

```
Traceback (most recent call last):
  File "sdtest/dist/sdtest.app/Contents/Resources/__boot__.py", line 77, in <module>
    _run()
  File "sdtest/dist/sdtest.app/Contents/Resources/__boot__.py", line 62, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "sdtest/dist/sdtest.app/Contents/Resources/sdtest.py", line 1, in <module>
    import sounddevice
  File "sounddevice.pyc", line 313, in <module>
  File "cffi/api.pyc", line 105, in cdef
  File "cffi/api.pyc", line 119, in _cdef
  File "cffi/cparser.pyc", line 299, in parse
  File "cffi/cparser.pyc", line 304, in _internal_parse
  File "cffi/cparser.pyc", line 260, in _parse
  File "cffi/cparser.pyc", line 40, in _get_parser
  File "pycparser/c_parser.pyc", line 116, in __init__
  File "pycparser/ply/yacc.pyc", line 3293, in yacc
  File "pycparser/ply/yacc.pyc", line 2938, in validate_all
  File "pycparser/ply/yacc.pyc", line 2982, in validate_modules
  File "inspect.pyc", line 690, in getsourcelines
  File "inspect.pyc", line 538, in findsource
IOError: could not get source code
```

Deep down in `ply.yacc.validate_modules()`, during a "sanity check" routine, it blows up because a module (in my particular case, `dist/sdtest.app/Contents/Resources/lib/python2.7/site-packages.zip/pycparser/plyparser.pyc`) doesn't have its .py source available. 

Given that `validate_modules()` is just a sanity check function, whose only purpose appears to be the side effect of issuing warnings, it doesn't make much sense for it to have such a fatal ending. 

Unless you think I'm way off track here, I'll submit a PR which eats the `IOError` in the case where source for a module is unavailable. And if I *am* way off track, I'd appreciate any feedback you could provide!

**Comment by riggsd** [comment]
OOPS! I checked out the upstream `ply` source only to find that this exact change has already made it into version 3.10.

It turns out that `pycparser` includes a *copy* of the `ply` source in its repository, and that version is the dusty old 3.8.

This bug has already been fixed! Please allow me to offer a retroactive THANK YOU!

I'll contact the `pycparser` project and encourage them to update their `ply` dependency.
