### ISSUE TITLE
How to add caching for a large grammar file

### ISSUE THREAD

**Issue by jnoortheen** [dabeaz/ply#253]
I am trying the latest ply version from the master branch for the [xonsh](https://github.com/xonsh/xonsh/) project. 
It takes around 3s to build the parser without a cache file. It is suggested to handle the caching by ourselves. I am not able to find a way to cache, without updating the `yacc.yacc` function's `LRTable` creation lines. Please provide an example if there is any other straightforward way.

**Comment by dabeaz** [comment]
In theory, it should be possible to cache the generated grammar using pickle.  That is, take the result of `yacc.yacc()` and pickle it to a file or someplace where you can get it back.

**Comment by jnoortheen** [comment]
Thanks for the fast reply. I tried pickling the result from `yacc` function. It resulted in error

```
Traceback (most recent call last):
  File "/src/shell/xsh/xonsh/ptk_shell/shell.py", line 324, in _push
    code = self.execer.compile(src, mode="single", glbs=self.ctx, locs=None)
    │      │                   │                        └ <xonsh.ptk_shell.shell.PromptToolkitShell object at 0x7fb570438a30>
    │      │                   └ 'exit\n'
    │      └ <xonsh.ptk_shell.shell.PromptToolkitShell object at 0x7fb570438a30>
    └ None
  File "/src/shell/xsh/xonsh/execer.py", line 135, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
           │          │      │         │              │                   └ True
           │          │      │         │              └ '<xonsh-code>'
           │          │      │         └ 'single'
           │          │      └ {'SystemError', '__loader__', 'StopAsyncIteration', 'IsADirectoryError', 'id', 'lstrip', 'abbrevs', 'DeprecationWarning', 'slice...
           │          └ 'exit\n'
           └ <xonsh.execer.Execer object at 0x7fb570d28d30>
  File "/src/shell/xsh/xonsh/execer.py", line 95, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
          │       │                    │           │              └ '<xonsh-code>'
          │       │                    │           └ 'single'
          │       │                    └ 'exit\n'
          │       └ <xonsh.execer.Execer object at 0x7fb570d28d30>
          └ 'exit\n'
  File "/src/shell/xsh/xonsh/execer.py", line 219, in _parse_ctx_free
    tree = self.parser.parse(
  File "/src/shell/xsh/xonsh/parsers/base.py", line 530, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
           │                       │        │                 └ False
           │                       │        └ <xonsh.parsers.v39.Parser object at 0x7fb570d28d90>
           │                       └ 'exit\n'
           └ <xonsh.parsers.v39.Parser object at 0x7fb570d28d90>
  File "/src/shell/xsh/xonsh/ply/ply/yacc.py", line 409, in parse
    p.callable(pslice)
    │          └ <xonsh.ply.ply.yacc.YaccProduction object at 0x7fb57189ddf0>
    └ Production(name_tok -> NAME)
  File "/src/shell/xsh/xonsh/parsers/base.py", line 589, in tokfunc
    raise TypeError("token for {0!r} not found.".format(rulename))
                                                        └ 'name'
TypeError: token for 'name' not found.

```

**Comment by jnoortheen** [comment]
seems like the error is raised because of p_dict refers to old object instance.

**Comment by dabeaz** [comment]
Is this an inherent feature of PLY or a facet of the program you're working with?    I'll investigate.

**Comment by jnoortheen** [comment]
it is more like the issue is because of passing yacc(module=self) and the p_* functions have reference to the old object instance. After pickling the whole `Parser` instance (the one with p_* methods and attribute to `yacc()` result) it raised some other errors. Finally I made the pickling work with [`dill`](https://dill.readthedocs.io/)

**Comment by jnoortheen** [comment]
I ended using the following snippet to pickle the parser instance

```py

def bind_callables(parser: yacc.LRParser, module: tp.Optional["Loader"]) -> None:
    parser.errorfunc = module.p_error if module else None
    for prod in parser.productions:
        if prod.func and module:
            prod.callable = getattr(module, prod.func)
        else:
            prod.callable = None

class Loader(...):
    def __init__(...):
        ...
        parser_cache = Path(__file__).absolute().parent / "parser.tmp.out"
        if parser_cache.exists():
            self.parser: yacc.LRParser = pickle.loads(
                parser_cache.read_bytes(),
            )
            print(time.time() - t, "took to load pickle")
            bind_callables(self.parser, self)
        else:
            self.parser = yacc.yacc(**yacc_kwargs)
            pickled = pickle.dumps(self.parser, protocol=5)
            bind_callables(self.parser, None)
            parser_cache.write_bytes(pickletools.optimize(pickled))
            bind_callables(self.parser, self)

```
