### ISSUE TITLE
sequence item 0: expected str instance, float found

### ISSUE THREAD

**Issue by myname1111** [dabeaz/ply#256]
I was creating an interpreter when i found this problem
```
Traceback (most recent call last):
  File "C:\Users\USER\PycharmProjects\Calico\Calico\Calico.py", line 476, in <module>
    parser = yacc.yacc()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\ply\yacc.py", line 3285, in yacc
    signature = pinfo.signature()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\ply\yacc.py", line 2986, in signature
    return ''.join(parts)
TypeError: sequence item 0: expected str instance, float found
```
this is the code
```
precedence = (

    ("left", "NEWLINE"),
    ("none", "DOT"),
    ("none", "COMMA"),
    ("none", "while"),
    ("none", "call", "tuple"),
    ("none", "elif", "ELSE"),
    ("none", "if"),
    ("nonassoc", "LESS", "MORE", "LEEQ", "MOEQ"),
    ("left", "PLUS", "MINUS"),
    ("left", "MULTIPLY", "DIVIDE"),
    ("left", "PAR", "PAL"),
    ('right', 'UMINUS'),

)


def p_line(p):
    """
    calc : calc NEWLINE calc
    """
    if p[1] == "main":
        p[0] = (p[1],) + (p[3],)
    else:
        p[0] = ("main",) + (p[1],) + (p[3],)


def p_fuc_call(p):
    """
    call : NAME tuple
         | var_name tuple
    """
    p[0] = ("call", p[1], p[2])


def p_class_call(p):
    """
    call : CLASS NAME tuple
         | CLASS var_name tuple
    """
    p[0] = ("class_call", p[1], p[2])


def p_main(p):
    """
    main : main NEWLINE main
    """
    print(p[1])
    if p[1] == "main":
        p[0] = (p[1],) + (p[3],)
    else:
        p[0] = (p[1],) + (p[3],)


def p_main_floor(p):
    """
    main : class
    """
    p[0] = p[1]


def p_calc(p):
    """
    calc : if
         | expression
         | var_assign
         | data
         | empty
         | while
         | method
         | output
         | comment
         | class
         | pv_class
    """
    p[0] = p[1]


def p_if_else(p):
    """
    if : IF RBRAC calc LBRAC RBRAC calc LBRAC elif
    """
    p[0] = ("if", p[3], p[6], p[8])


def p_var_assign(p):
    """
    var_assign : var_name EQUALS expression
               | var_name EQUALS data
    """
    p[0] = ("=", p[1], p[3])


def p_var_assign_class(p):
    """
    var_assign : PUBLIC var_name EQUALS expression
               | PUBLIC var_name EQUALS data
               | PRIVATE var_name EQUALS expression
               | PRIVATE var_name EQUALS data
    """
    p[0] = ("=", p[2], p[4], p[1])


def elif_floor(p):
    """
    elif : ELSE RBRAC calc LBRAC
    """
    p[0] = ("else", p[3])


def p_if(p):
    """
    if : IF RBRAC calc LBRAC RBRAC calc LBRAC
    """
    p[0] = ("if", p[3], p[6])


def p_expression_uminus(p):
    """expression : MINUS expression %prec UMINUS"""
    p[0] = -p[2]


def p_expression(p):
    """
    expression : expression MULTIPLY expression
               | expression DIVIDE expression
               | expression PLUS expression
               | expression MINUS expression
               | expression MORE expression
               | expression LESS expression
               | expression MOEQ expression
               | expression LEEQ expression
               | expression DEQUALS expression
    """
    p[0] = (p[2], p[1], p[3])


def p_expression_floor(p):
    """
    expression : INT
               | FLOAT
               | call
               | TRUE
               | FALSE
    """
    p[0] = p[1]


def p_expression_par(p):
    """
    expression : PAL expression PAR
    """
    p[0] = p[2]


def p_expression_var(p):
    """
    expression : NAME
               | var_name
    """
    p[0] = ("var", p[1])


def p_expression_var_dot(p):
    """
    var_name : NAME DOT NAME
    """
    p[0] = (".", ("var", p[1]), ("var", p[3]))


def p_expression_var_dot_floor_2(p):
    """
    var_name : NAME DOT var_name
    """

    p[0] = (".", ("var", p[1]), p[3])


def p_expression_var_dot_floor(p):
    """
    var_name : NAME
    """
    p[0] = p[1]


def p_data_floor(p):
    """
    data : expression
         | INT
         | FLOAT
         | tuple
         | string
         | empty
    """
    p[0] = (p[1],)


def p_comma(p):
    """
    data : data COMMA data
    """
    p[0] = tuple(list(p[1]) + list(p[3]))


def p_string(p):
    """
    string : STRING
    """
    p[0] = ("string", p[1])


def p_tuple(p):
    """
    tuple : PAL data PAR
    """
    p[0] = ("tuple", p[2])


def p_while(p):
    """
    while : WHILE RBRAC expression LBRAC RBRAC calc LBRAC
    """
    p[0] = ("while", p[3], p[6])


def p_return(p):
    """
    output : RETURN expression
           | RETURN data
    """
    p[0] = ("output", p[2])


def p_def(p):
    """
    method : PUBLIC NAME tuple RBRAC calc LBRAC
           | PRIVATE NAME tuple RBRAC calc LBRAC
    """
    p[0] = ("func", p[2], p[5], p[3], p[1], False)


def p_static(p):
    """
    method : PUBLIC STATIC NAME tuple RBRAC calc LBRAC
           | PRIVATE STATIC NAME tuple RBRAC calc LBRAC
    """
    p[0] = ("func", p[3], p[6], p[4], p[1], p[2])


def p_class(p):
    """
    class : CLASS NAME RBRAC calc LBRAC
    """
    p[0] = ("class", p[2], p[4])


def p_class_inherit(p):
    """
    class : CLASS NAME NAME RBRAC calc LBRAC
    """
    p[0] = ("class", p[2], p[3], p[5])


def p_p_class(p):
    """
    pv_class : PRIVATE class
    """
    p[0] = tuple(p[2] + [p[1]])


def p_elif(p):
    """
    elif : ELIF RBRAC calc LBRAC RBRAC calc LBRAC
    """
    p[0] = ("elif", p[3], p[6])


def p_elif_else(p):
    """
    elif : ELIF RBRAC calc LBRAC RBRAC calc LBRAC elif
    """
    p[0] = ("elif", p[3], p[6], p[9])


def p_elif_else_floor(p):
    """
    elif : ELSE RBRAC calc LBRAC
    """
    p[0] = ("else", p[3])


def p_empty_com(p):
    """
    empty : none
          | comment
    """
    p[0] = p[1]


def p_empty(p):
    """
    none :
    """
    p[0] = None


def p_comment(p):
    """
    comment : COMMENT
    """
    p[0] = None


def p_error(p):
    print(f"Error detected:{p.type} at line {p.lineno}")
```

**Comment by myname1111** [comment]
Sorry so after a tracking down and the issue i have this piece causing all of this

```
start = time.time()
```
i'd recommend a list of names you shouldn't name your variables , sorry
