### ISSUE TITLE
PLY not compatible with python 3.12

### ISSUE THREAD

**Issue by slicetext** [dabeaz/ply#288]
I downloaded PLY from the website. However, when trying to run `python3 setup.py install`, it gave me  
```
/home/owner/Downloads/ply-3.11/setup.py:4: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.core import setup
Traceback (most recent call last):
  File "/home/owner/Downloads/ply-3.11/setup.py", line 2, in <module>
    from setuptools import setup
ModuleNotFoundError: No module named 'setuptools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/owner/Downloads/ply-3.11/setup.py", line 4, in <module>
    from distutils.core import setup
ModuleNotFoundError: No module named 'distutils.core'

```
 How do I fix this?

**Comment by hugovk** [comment]
Don't run `setup.py` directly, install via pip:

```console
❯ python3.12 -m pip install .
Processing /private/tmp/ply
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: ply
  Building wheel for ply (pyproject.toml) ... done
  Created wheel for ply: filename=ply-2022.10.27-py3-none-any.whl size=32918 sha256=a0f1bbdd5c05cb5c970024590c5129d4c32a79962acc2a98b43ada7c00de6521
  Stored in directory: /private/var/folders/p6/lf2s1s5d4kb335g2n1td8z8c0000gn/T/pip-ephem-wheel-cache-tpvn2k0e/wheels/88/ef/05/2f943383a0eabc3a4eea06256dffaad1aadfb04b4645b498f8
Successfully built ply
Installing collected packages: ply
Successfully installed ply-2022.10.27

❯ python3.12 tests/testlex.py
/private/tmp/ply/tests/testlex.py:193: SyntaxWarning: invalid escape sequence '\#'
  "ERROR: Make sure '#' in rule 't_POUND' is escaped with '\#'")
.....................................
----------------------------------------------------------------------
Ran 37 tests in 0.046s

OK

❯ python3.12 tests/testyacc.py
....................................
----------------------------------------------------------------------
Ran 36 tests in 0.030s

OK
```

The long version: https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
