### ISSUE TITLE
Test failures with Python 3.3

### ISSUE THREAD

**Issue by Arfrever** [dabeaz/ply#34]
Some tests fail randomly with Python 3.3 due to hash randomization. Test suite might need to be run multiple times to reproduce all failures.
```
$ python3.3 testyacc.py
======================================================================
FAIL: test_yacc_inf (__main__.YaccErrorWarningTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testyacc.py", line 209, in test_yacc_inf
    "Token 'NUMBER' defined, but not used\n"
AssertionError: False is not true

======================================================================
FAIL: test_yacc_prec1 (__main__.YaccErrorWarningTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testyacc.py", line 368, in test_yacc_prec1
    "Precedence rule 'left' defined for unknown symbol '+'\n"
AssertionError: False is not true

======================================================================
FAIL: test_yacc_rr (__main__.YaccErrorWarningTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testyacc.py", line 288, in test_yacc_rr
    "Generating LALR tables\n"
AssertionError: False is not true

======================================================================
FAIL: test_yacc_rr_unused (__main__.YaccErrorWarningTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testyacc.py", line 299, in test_yacc_rr_unused
    "no p_error() function is defined\n"
AssertionError: False is not true

======================================================================
FAIL: test_yacc_unused (__main__.YaccErrorWarningTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testyacc.py", line 336, in test_yacc_unused
    "yacc_unused.py:62: Symbol 'COMMA' used, but not defined as a token or a rule\n"
AssertionError: False is not true

----------------------------------------------------------------------
```

**Comment by dabeaz** [comment]
This appears to be fixed in current github.
