### ISSUE TITLE
Errors in the testsuite in testlex.py and python 2.7.5 on RHEL-7

### ISSUE THREAD

**Issue by mcepl** [dabeaz/ply#54]
```
matej@mitmanek: test$ python testlex.py
.F..FFF...................................
======================================================================
FAIL: test_lex_many_tokens (__main__.LexBuildOptionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testlex.py", line 544, in test_lex_many_tokens
    self.assert_(os.path.exists("manytab.py"))
AssertionError: False is not true

======================================================================
FAIL: test_lex_opt_alias (__main__.LexBuildOptionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testlex.py", line 487, in test_lex_opt_alias
    self.assert_(os.path.exists("aliastab.py"))
AssertionError: False is not true

======================================================================
FAIL: test_lex_optimize (__main__.LexBuildOptionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testlex.py", line 342, in test_lex_optimize
    self.assert_(os.path.exists("lextab.py"))
AssertionError: False is not true

======================================================================
FAIL: test_lex_optimize2 (__main__.LexBuildOptionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testlex.py", line 396, in test_lex_optimize2
    self.assert_(os.path.exists("opt2tab.py"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 42 tests in 0.101s

FAILED (failures=4)
matej@mitmanek: test$ python -V
Python 2.7.5
matej@mitmanek: test$
```
Using `pyl` 3.4 installed from pypi.

**Comment by dabeaz** [comment]
Not reproducible for me.
