### ISSUE TITLE
Chromium build error with ply-3.6

### ISSUE THREAD

**Issue by floppym** [dabeaz/ply#66]
Attempting to build the Chromium web browser using ply-3.6 fails with the following error:

```
[351/17437] cd ../../third_party/WebKit/Source/bindings/scripts; python blink_idl_parser.py ../../../../../out/Release/gen/blink/bindings/scripts
FAILED: cd ../../third_party/WebKit/Source/bindings/scripts; python blink_idl_parser.py ../../../../../out/Release/gen/blink/bindings/scripts
Traceback (most recent call last):
  File "blink_idl_parser.py", line 456, in <module>
    sys.exit(main(sys.argv))
  File "blink_idl_parser.py", line 452, in main
    parser = BlinkIDLParser(outputdir=outputdir, rewrite_tables=True)
  File "blink_idl_parser.py", line 428, in __init__
    picklefile=picklefile)
  File "/usr/lib64/python2.7/site-packages/ply/yacc.py", line 3242, in yacc
    read_signature = lr.read_pickle(picklefile)
  File "/usr/lib64/python2.7/site-packages/ply/yacc.py", line 1986, in read_pickle
    in_f = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: '../../../../../out/Release/gen/blink/bindings/scripts/parsetab.pickle'
```

The relevant script is here:

https://chromium.googlesource.com/chromium/blink/+/master/Source/bindings/scripts/blink_idl_parser.py

I think it passes a picklefile to yacc.yacc() which is not expected to exist; ply-3.4 would allow this without error, and I think it would write a picklefile for future use.

Does that sound right? Or is this script doing something wrong?

**Comment by dabeaz** [comment]
Fixed in 3.7.
