### ISSUE TITLE
Missing pickle file (or perhaps a misspelled file path) 

### ISSUE THREAD

**Issue by courtyardz** [dabeaz/ply#73]
When ply (dependency of Todoflow python module) calls its internal function yacc(...,picklefile=None), it is calling it with a picklefile that does not exist: /Users/my_account/.todoflow_parsetab.pickle. Please see my simple script below and the error output. Notice that in the last line of the error output, there is a u in front of the file path. This may be causing the issue, but I haven't yet found out when it gets put there...

FYI I am running El Cap public beta, ply (3.6), Todoflow (4.0.1). Perhaps this is instead a Todoflow issue?

## todoflow_now.py:

```python
#!/usr/local/bin/python
# return query of tasks to be added to reminders Now list

import sys
import os
import time

#sys.path.append('/usr/local/lib/python2.7/site-packages/')
import todoflow

curDate = time.strftime("%Y-%m-%d")
todos = todoflow.from_path('~/Dropbox/Notes/test.taskpaper')

#def get_project(iterable):

for item in todos.search('((@today or @focus or @overdue or @next or @due <= ' & curDate & ' ) and not @done)+d'):
    print item
    #item.tag('@done', curDate)
    #item.remove_tag('@today')
```

## error messages:

```python
$ todoflow_now.py 
Traceback (most recent call last):
  File "/Users/my_account/bin/todoflow_now.py", line 8, in <module>
    import todoflow
  File "/usr/local/lib/python2.7/site-packages/todoflow/__init__.py", line 3, in <module>
    from .todoflow import from_text, from_path, from_paths, from_dir
  File "/usr/local/lib/python2.7/site-packages/todoflow/todoflow.py", line 4, in <module>
    from .parser import parse
  File "/usr/local/lib/python2.7/site-packages/todoflow/parser.py", line 4, in <module>
    from .todos import Todos, Node
  File "/usr/local/lib/python2.7/site-packages/todoflow/todos.py", line 5, in <module>
    from .querying_parser import parse as parse_query
  File "/usr/local/lib/python2.7/site-packages/todoflow/querying_parser.py", line 247, in <module>
    debug=0, write_tables=0,
  File "/usr/local/lib/python2.7/site-packages/ply/yacc.py", line 3242, in yacc
    read_signature = lr.read_pickle(picklefile)
  File "/usr/local/lib/python2.7/site-packages/ply/yacc.py", line 1986, in read_pickle
    in_f = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: u'/Users/my_account/.todoflow_parsetab.pickle'
```

**Comment by joeedh** [comment]
Okay, I've submitted a pull request fixing the bug.  Until it (or someone else's fix) gets committed, you pull from [here](https://github.com/joeedh/ply).  Or just look at the pull requests tab, you should be able to download patch.

**Comment by courtyardz** [comment]
Great. Much thanks @joeedh. The existence check fixed the issue for me.

**Comment by joeedh** [comment]
No problem.

**Comment by dabeaz** [comment]
Fixed.
