### ISSUE TITLE
Python 3.5 compatibility

### ISSUE THREAD

**Issue by warsaw** [dabeaz/ply#76]
Several testlex.py failures under Python 3.5:

```
% python3.5 testlex.py
....F/usr/lib/python3.5/unittest/case.py:625: ResourceWarning: unclosed file <_io.BufferedReader name=4>
  outcome.errors.clear()
FFF.............F.F..................
======================================================================
FAIL: test_lex_opt_alias (__main__.LexBuildOptionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testlex.py", line 541, in test_lex_opt_alias
    self.assert_(pymodule_out_exists("aliastab.pyo"))
AssertionError: False is not true

======================================================================
FAIL: test_lex_optimize (__main__.LexBuildOptionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testlex.py", line 390, in test_lex_optimize
    self.assert_(pymodule_out_exists("lextab.pyo"))
AssertionError: False is not true

======================================================================
FAIL: test_lex_optimize2 (__main__.LexBuildOptionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testlex.py", line 443, in test_lex_optimize2
    self.assert_(pymodule_out_exists("opt2tab.pyo"))
AssertionError: False is not true

======================================================================
FAIL: test_lex_optimize3 (__main__.LexBuildOptionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testlex.py", line 494, in test_lex_optimize3
    self.assert_(pymodule_out_exists("lexdir/sub/calctab.pyo"))
AssertionError: False is not true

======================================================================
FAIL: test_lex_re1 (__main__.LexErrorWarningTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testlex.py", line 161, in test_lex_re1
    contains=True))
AssertionError: False is not true

======================================================================
FAIL: test_lex_re3 (__main__.LexErrorWarningTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testlex.py", line 179, in test_lex_re3
    contains=True))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 42 tests in 1.595s

FAILED (failures=6)
```

**Comment by warsaw** [comment]
https://github.com/dabeaz/ply/pull/78

Adjusts for PEP 488 and different re error messages in Python 3.5
